// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmog_algorithm_block.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMog_algorithm_block_CfgInitialize(XMog_algorithm_block *InstancePtr, XMog_algorithm_block_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Hls_fgbg_periph_bus_BaseAddress = ConfigPtr->Hls_fgbg_periph_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMog_algorithm_block_Start(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL) & 0x80;
    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMog_algorithm_block_IsDone(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMog_algorithm_block_IsIdle(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMog_algorithm_block_IsReady(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMog_algorithm_block_EnableAutoRestart(XMog_algorithm_block *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL, 0x80);
}

void XMog_algorithm_block_DisableAutoRestart(XMog_algorithm_block *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL, 0);
}

void XMog_algorithm_block_SetWidth(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_WIDTH_DATA, Data);
}

u32 XMog_algorithm_block_GetWidth(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_WIDTH_DATA);
    return Data;
}

void XMog_algorithm_block_SetC_alpha(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_ALPHA_DATA, Data);
}

u32 XMog_algorithm_block_GetC_alpha(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_ALPHA_DATA);
    return Data;
}

void XMog_algorithm_block_SetC_vinit(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VINIT_DATA, Data);
}

u32 XMog_algorithm_block_GetC_vinit(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VINIT_DATA);
    return Data;
}

void XMog_algorithm_block_SetC_varth(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VARTH_DATA, Data);
}

u32 XMog_algorithm_block_GetC_varth(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VARTH_DATA);
    return Data;
}

void XMog_algorithm_block_SetC_winit(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_WINIT_DATA, Data);
}

u32 XMog_algorithm_block_GetC_winit(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_WINIT_DATA);
    return Data;
}

void XMog_algorithm_block_SetC_bgth(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_BGTH_DATA, Data);
}

u32 XMog_algorithm_block_GetC_bgth(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_BGTH_DATA);
    return Data;
}

void XMog_algorithm_block_SetFlags(XMog_algorithm_block *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_FLAGS_DATA, Data);
}

u32 XMog_algorithm_block_GetFlags(XMog_algorithm_block *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_FLAGS_DATA);
    return Data;
}

void XMog_algorithm_block_InterruptGlobalEnable(XMog_algorithm_block *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_GIE, 1);
}

void XMog_algorithm_block_InterruptGlobalDisable(XMog_algorithm_block *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_GIE, 0);
}

void XMog_algorithm_block_InterruptEnable(XMog_algorithm_block *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER);
    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER, Register | Mask);
}

void XMog_algorithm_block_InterruptDisable(XMog_algorithm_block *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER);
    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER, Register & (~Mask));
}

void XMog_algorithm_block_InterruptClear(XMog_algorithm_block *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMog_algorithm_block_WriteReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_ISR, Mask);
}

u32 XMog_algorithm_block_InterruptGetEnabled(XMog_algorithm_block *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER);
}

u32 XMog_algorithm_block_InterruptGetStatus(XMog_algorithm_block *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMog_algorithm_block_ReadReg(InstancePtr->Hls_fgbg_periph_bus_BaseAddress, XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_ISR);
}

