// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// HLS_FGBG_PERIPH_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of width
//        bit 15~0 - width[15:0] (Read/Write)
//        others   - reserved
// 0x18 : reserved
// 0x1c : Data signal of c_alpha
//        bit 31~0 - c_alpha[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of c_vinit
//        bit 31~0 - c_vinit[31:0] (Read/Write)
// 0x28 : reserved
// 0x2c : Data signal of c_varth
//        bit 31~0 - c_varth[31:0] (Read/Write)
// 0x30 : reserved
// 0x34 : Data signal of c_winit
//        bit 31~0 - c_winit[31:0] (Read/Write)
// 0x38 : reserved
// 0x3c : Data signal of c_bgth
//        bit 31~0 - c_bgth[31:0] (Read/Write)
// 0x40 : reserved
// 0x44 : Data signal of flags
//        bit 31~0 - flags[31:0] (Read/Write)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_AP_CTRL      0x00
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_GIE          0x04
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_IER          0x08
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_ISR          0x0c
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_WIDTH_DATA   0x14
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_WIDTH_DATA   16
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_ALPHA_DATA 0x1c
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_C_ALPHA_DATA 32
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VINIT_DATA 0x24
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_C_VINIT_DATA 32
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_VARTH_DATA 0x2c
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_C_VARTH_DATA 32
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_WINIT_DATA 0x34
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_C_WINIT_DATA 32
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_C_BGTH_DATA  0x3c
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_C_BGTH_DATA  32
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_ADDR_FLAGS_DATA   0x44
#define XMOG_ALGORITHM_BLOCK_HLS_FGBG_PERIPH_BUS_BITS_FLAGS_DATA   32

