// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmog_algorithm_block.h"

extern XMog_algorithm_block_Config XMog_algorithm_block_ConfigTable[];

XMog_algorithm_block_Config *XMog_algorithm_block_LookupConfig(u16 DeviceId) {
	XMog_algorithm_block_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMOG_ALGORITHM_BLOCK_NUM_INSTANCES; Index++) {
		if (XMog_algorithm_block_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMog_algorithm_block_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMog_algorithm_block_Initialize(XMog_algorithm_block *InstancePtr, u16 DeviceId) {
	XMog_algorithm_block_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMog_algorithm_block_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMog_algorithm_block_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

