
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmog_algorithm_block.h"

/*
* The configuration table for devices
*/

XMog_algorithm_block_Config XMog_algorithm_block_ConfigTable[] =
{
	{
		XPAR_MOG_ALGORITHM_BLOCK_0_DEVICE_ID,
		XPAR_MOG_ALGORITHM_BLOCK_0_S_AXI_HLS_FGBG_PERIPH_BUS_BASEADDR
	}
};


