
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhls_macc.h"

/*
* The configuration table for devices
*/

XHls_macc_Config XHls_macc_ConfigTable[] =
{
	{
		XPAR_HLS_MACC_0_DEVICE_ID,
		XPAR_HLS_MACC_0_S_AXI_AXI4LITES_BASEADDR
	}
};


