// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xhls_macc.h"
#include "xil_assert.h"
/*typedef struct {
    u16 DeviceId;
    u32 Axi4lites_BaseAddress;
} XHls_macc_Config;*/

/************************** Function Implementation *************************/
//#ifndef __linux__
int XHls_macc_CfgInitialize(XHls_macc *InstancePtr, XHls_macc_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
//#endif

void XHls_macc_Start(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL) & 0x80;
    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHls_macc_IsDone(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHls_macc_IsIdle(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHls_macc_IsReady(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHls_macc_EnableAutoRestart(XHls_macc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL, 0x80);
}

void XHls_macc_DisableAutoRestart(XHls_macc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_AP_CTRL, 0);
}

void XHls_macc_SetA(XHls_macc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_A_DATA, Data);
}

u32 XHls_macc_GetA(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_A_DATA);
    return Data;
}

void XHls_macc_SetB(XHls_macc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_B_DATA, Data);
}

u32 XHls_macc_GetB(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_B_DATA);
    return Data;
}

u32 XHls_macc_GetAccum(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_ACCUM_DATA);
    return Data;
}

u32 XHls_macc_GetFlag(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_FLAG_DATA);
    return Data;
}

void XHls_macc_SetAccum_clr(XHls_macc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_ACCUM_CLR_DATA, Data);
}

u32 XHls_macc_GetAccum_clr(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_ACCUM_CLR_DATA);
    return Data;
}

void XHls_macc_SetByte_wroffset(XHls_macc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_BYTE_WROFFSET_DATA, Data);
}

u32 XHls_macc_GetByte_wroffset(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_BYTE_WROFFSET_DATA);
    return Data;
}

void XHls_macc_SetFrame_len(XHls_macc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_FRAME_LEN_DATA, Data);
}

u32 XHls_macc_GetFrame_len(XHls_macc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_FRAME_LEN_DATA);
    return Data;
}

void XHls_macc_InterruptGlobalEnable(XHls_macc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_GIE, 1);
}

void XHls_macc_InterruptGlobalDisable(XHls_macc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_GIE, 0);
}

void XHls_macc_InterruptEnable(XHls_macc *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_IER);
    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_IER, Register | Mask);
}

void XHls_macc_InterruptDisable(XHls_macc *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_IER);
    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_IER, Register & (~Mask));
}

void XHls_macc_InterruptClear(XHls_macc *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_macc_WriteReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_ISR, Mask);
}

u32 XHls_macc_InterruptGetEnabled(XHls_macc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_IER);
}

u32 XHls_macc_InterruptGetStatus(XHls_macc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_macc_ReadReg(InstancePtr->Axi4lites_BaseAddress, XHLS_MACC_AXI4LITES_ADDR_ISR);
}

